on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [1.8]

    steps:
    - uses: actions/checkout@v1
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.0.1
      if: ${{ matrix.os == 'windows-latest' }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle on Ubuntu
      run: |
        source scripts/android-setup.sh && installAndroidSDK
        ./gradlew assembleDebug
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Run tests on Ubuntu
      run: |
        source scripts/android-setup.sh && installAndroidSDK && installsdk 'cmake;3.10.2.4988404'
        scripts/run-host-tests.sh
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Build with Gradle on Windows
      run: |
        echo "Windows build here"
      if: ${{ matrix.os == 'windows-latest' }}
    - name: Run tests on Windows
      run: |
        echo "Windows tests here"
      if: ${{ matrix.os == 'windows-latest' }}
